db:
  driver:   pdo_mysql
  name:   digex
  host:     localhost
  user:     root
  password:

em:
  entities: [src/Digitas/Demo/Entity]
  fixtures:  [src/Digitas/Demo/DataFixtures/ORM]

translator:
  locale_fallback: en_UK
  locales:
    fr_FR: fr_FR.yml