#!/usr/bin/env php
<?php

// This will let the permissions be 0777
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/../src/autoload.php';

use Symfony\Component\Console\Input\ArgvInput;
use Digex\Console;
use Digex\Provider\ConsoleServiceProvider;

$input = new ArgvInput();

$app = new Silex\Application();
$app->register(new ConsoleServiceProvider());

$app['app_dir'] = __DIR__.'/../app';
$app['vendor_dir'] = __DIR__.'/../vendor/silex/vendor';
$app['debug'] = !$input->hasParameterOption(array('--no-debug', ''));
$app['env'] = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');

$app['console']->run();